version: '3.5'

services:

  flask-api:
    container_name: flask-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=api.py

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '/usr/src/app/node_modules'
    ports:
      - 80:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - flask-api